{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "126ff5a1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app '__main__'\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\n",
      " * Running on http://127.0.0.1:5000\n",
      "Press CTRL+C to quit\n",
      "127.0.0.1 - - [24/May/2024 18:04:40] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/May/2024 18:04:40] \"GET /favicon.ico HTTP/1.1\" 404 -\n",
      "127.0.0.1 - - [24/May/2024 18:04:47] \"POST /calculate HTTP/1.1\" 302 -\n",
      "127.0.0.1 - - [24/May/2024 18:04:47] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/May/2024 18:05:38] \"POST /calculate HTTP/1.1\" 302 -\n",
      "127.0.0.1 - - [24/May/2024 18:05:38] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/May/2024 18:06:03] \"POST /calculate HTTP/1.1\" 302 -\n",
      "127.0.0.1 - - [24/May/2024 18:06:03] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/May/2024 18:06:17] \"POST /deletecookie HTTP/1.1\" 302 -\n",
      "127.0.0.1 - - [24/May/2024 18:06:17] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/May/2024 18:06:24] \"POST /calculate HTTP/1.1\" 302 -\n",
      "127.0.0.1 - - [24/May/2024 18:06:24] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/May/2024 18:06:45] \"POST /calculate HTTP/1.1\" 302 -\n",
      "127.0.0.1 - - [24/May/2024 18:06:45] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/May/2024 18:07:44] \"POST /calculate HTTP/1.1\" 302 -\n",
      "127.0.0.1 - - [24/May/2024 18:07:44] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/May/2024 18:08:13] \"POST /calculate HTTP/1.1\" 302 -\n",
      "127.0.0.1 - - [24/May/2024 18:08:13] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/May/2024 18:09:08] \"POST /deletecookie HTTP/1.1\" 302 -\n",
      "127.0.0.1 - - [24/May/2024 18:09:08] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/May/2024 18:09:17] \"POST /calculate HTTP/1.1\" 302 -\n",
      "127.0.0.1 - - [24/May/2024 18:09:17] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [24/May/2024 18:47:56] \"POST /export-csv HTTP/1.1\" 200 -\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask, render_template, request, redirect, make_response, send_file, flash, Response\n",
    "import json\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import csv\n",
    "from collections import defaultdict\n",
    "\n",
    "from io import StringIO\n",
    "app = Flask(__name__)\n",
    "app.secret_key = '123456'\n",
    "headers = {\"User-Agent\": \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36\"}\n",
    "\n",
    "def getSoup(url):\n",
    "    response = requests.get(url, headers=headers)\n",
    "    soup = BeautifulSoup(response.text, 'html.parser')\n",
    "    return soup \n",
    "\n",
    "def getWordCount(soup):\n",
    "    text = []\n",
    "    tags = soup.find_all([\"h1\", \"h2\", \"h3\", \"h4\", \"h5\", \"h6\", \"p\"])\n",
    "    for tag in tags:\n",
    "        text.append(tag.text.strip().split())\n",
    "    word_count = 0\n",
    "    for group in text:\n",
    "        for word in group:\n",
    "            word_count += 1\n",
    "    return word_count\n",
    "\n",
    "def getMetaTitle(soup):\n",
    "    title = soup.find(\"title\").text\n",
    "    return title\n",
    "\n",
    "def getHTagsNew(soup):\n",
    "    text = []\n",
    "    for tags in soup.find_all([\"h1\", \"h2\", \"h3\", \"h4\", \"h5\", \"h6\"]):\n",
    "        text.append({\"heading\": tags.name.upper(), \"text\": tags.text.strip()})\n",
    "    return text\n",
    "\n",
    "@app.route('/')\n",
    "def index():\n",
    "    urls_data = []\n",
    "    for key, value in request.cookies.items():\n",
    "        if key[0:4] == \"http\":\n",
    "            urls_data.append(json.loads(value))\n",
    "    return render_template(\"index.html\", urls_data=urls_data)\n",
    "\n",
    "@app.route('/calculate', methods=[\"POST\"])\n",
    "def calculate():\n",
    "    url = request.form[\"url\"]\n",
    "    soup = getSoup(url)\n",
    "    hTags = getHTagsNew(soup)\n",
    "    url_data = json.dumps({\"url\": url, \"word count\": getWordCount(soup), \"meta title\": getMetaTitle(soup), \"headings\": hTags})\n",
    "    resp = make_response(redirect('/'))\n",
    "    resp.set_cookie(url, url_data)\n",
    "    return resp\n",
    "\n",
    "@app.route('/export-csv', methods=['POST'])\n",
    "def exportCSV():\n",
    "    data = request.form.get('outlineData')\n",
    "    if data:\n",
    "        data = json.loads(data)\n",
    "        outline_data = data.get('outline', [])\n",
    "        additional_details = data.get('details', {})\n",
    "        output = StringIO()\n",
    "        thewriter = csv.writer(output)\n",
    "        \n",
    "        # Write headers for the columns\n",
    "        thewriter.writerow(['Tag', 'Details'])\n",
    "        \n",
    "        # Write additional details first (if any)\n",
    "        for detail_key, detail_value in additional_details.items():\n",
    "            # Assuming additional details also follow the format \"TAG:Details\"\n",
    "            tag, detail = detail_key.split(':', 1) if ':' in detail_key else (detail_key, detail_value)\n",
    "            thewriter.writerow([tag, detail])\n",
    "            \n",
    "        # Now process each item in the outline data\n",
    "        for item in outline_data:\n",
    "            # Split the item into tag and detail by the first occurrence of ':'\n",
    "            tag, detail = item.split(':', 1) if ':' in item else ('Unknown', item)\n",
    "            thewriter.writerow([tag.strip(), detail.strip()])\n",
    "        \n",
    "        output.seek(0)\n",
    "        response = Response(output.getvalue(), content_type='text/csv')\n",
    "        response.headers['Content-Disposition'] = 'attachment; filename=website-text-analyser.csv'\n",
    "        return response\n",
    "    else:\n",
    "        flash('No data to export.', 'error')\n",
    "        return redirect('/')\n",
    "\n",
    "@app.route('/clearcookies', methods=['POST'])\n",
    "def clearCookies():\n",
    "    resp = make_response(redirect('/'))\n",
    "    for key in request.cookies.keys():\n",
    "        resp.delete_cookie(key)\n",
    "    flash('All cookies cleared successfully!', 'success')\n",
    "    return resp\n",
    "\n",
    "@app.route('/deletecookie', methods=[\"POST\"])\n",
    "def deleteCookie():\n",
    "    cookieName = request.form[\"url\"]\n",
    "    resp = make_response(redirect('/'))\n",
    "    resp.set_cookie(cookieName, '', expires=0)\n",
    "    return resp\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run(debug=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e59600de",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
